export type { Icon } from 'react-feather';
export {
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Home as DashboardIcon,
  Download as DownloadIcon,
  Edit as EditIcon,
  XCircle as ErrorAlertIcon,
  LogOut as ExitIcon,
  FilePlus as FilePlusIcon,
  Home as HomeIcon,
  MoreHorizontal as MenuIcon,
  Package as PackageIcon,
  Users as PeopleIcon,
  Plus as PlusIcon,
  Trash2 as TrashIcon,
  Upload as UploadIcon,
  User as UserIcon,
  MoreVertical as VerticalMenuIcon,
} from 'react-feather';
