export type { Icon } from 'react-feather';
export {
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  Home as DashboardIcon,
  Edit as EditIcon,
  XCircle as ErrorAlertIcon,
  LogOut as ExitIcon,
  Home as HomeIcon,
  MoreHorizontal as MenuIcon,
  Package as PackageIcon,
  Users as PeopleIcon,
  Plus as PlusIcon,
  Trash2 as TrashIcon,
  User as UserIcon,
} from 'react-feather';
