export { ReactComponent as ChevronLeftIcon } from './ChevronLeft.svg';
export { ReactComponent as DashboardIcon } from './Dashboard.svg';
export { ReactComponent as ErrorAlertIcon } from './ErrorAlert.svg';
export { ReactComponent as ExitIcon } from './Exit.svg';
export { ReactComponent as HomeIcon } from './Home.svg';
export { ReactComponent as MenuIcon } from './Menu.svg';
export { ReactComponent as PackageIcon } from './Package.svg';
export { ReactComponent as PeopleIcon } from './People.svg';
export { ReactComponent as PlusIcon } from './Plus.svg';
