export const householderFormIds = {
  form: 'householder-form',
  firstNameInput: 'householder-first-name',
  lastNameInput: 'householder-last-name',
  fatherNameInput: 'householder-father-name',
  nationalityInput: 'householder-nationality',
  nationalIdInput: 'householder-nationalId',
  issuedAtInput: 'householder-issuedAt',
  religionInput: 'householder-religion',
  genderInput: 'householder-gender',
  dobInput: 'householder-date-of-birth',
  cityOfBirthInput: 'householder-city-of-birth',
  submitBtn: 'householder-submit-button',
  editBtn: 'householder-edit-button',
  cancel: 'householder-cancel-button',
} as const;
