export const householderIdentityFormIds = {
  form: 'householder-identity-form',
  firstNameInput: 'householder-first-name',
  lastNameInput: 'householder-last-name',
  fatherNameInput: 'householder-father-name',
  nationalityInput: 'householder-nationality',
  nationalIdInput: 'householder-nationalId',
  ssnInput: 'householder-ssn',
  issuedAtInput: 'householder-issuedAt',
  religionInput: 'householder-religion',
  genderInput: 'householder-gender',
  dateOfBirthInput: 'householder-date-of-birth',
  cityOfBirthInput: 'project-city-of-birth',
  submitBtn: 'submit-button',
} as const;
