import type { MantineThemeOverride } from '@mantine/core';

const toMantineColor = (color: string) =>
  // eslint-disable-next-line no-sparse-arrays
  [, , , , , , color] as [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    string,
  ];

export const theme: MantineThemeOverride = {
  dir: 'rtl',
  fontFamily: 'IRANSansFaNum',
  colors: {
    required: toMantineColor('#F03E3E'),
    fgDefault: toMantineColor('#212529'),
    fgMuted: toMantineColor('#495057'),
    fgSubtle: toMantineColor('#ADB5BD'),
    fgOnAccent: toMantineColor('#FFFFFF'),
    fgOnDisabled: toMantineColor('#ADB5BD'),
    fgDisabled: toMantineColor('#E9ECEF'),
    bgSurface: toMantineColor('#FFFFFF'),
    bgMuted: toMantineColor('#DEE2E6'),
    bgSubtle: toMantineColor('#F1F3F5'),
    bgCanvas: toMantineColor('#FAFAFA'),
    bgDisabled: toMantineColor('#F1F3F5'),
    borderDefault: toMantineColor('#CED4DA'),
    borderActive: toMantineColor('#339AF0'),
    ctaDefault: toMantineColor('#339AF0'),
    ctaEmphasized: toMantineColor('#228BE6'),
    ctaMuted: toMantineColor('#4DABF7'),
    ctaSubtle: toMantineColor('#D0EBFF'),
    ctaDisabled: toMantineColor('#CED4DA'),
    primaryDefault: toMantineColor('#4C6EF5'),
    primaryEmphasized: toMantineColor('#364FC7'),
    primaryMuted: toMantineColor('#748FFC'),
    primarySubtle: toMantineColor('#EDF2FF'),
    secondaryDefault: toMantineColor('#868E96'),
    secondaryEmphasized: toMantineColor('#495057'),
    secondaryMuted: toMantineColor('#ADB5BD'),
    secondarySubtle: toMantineColor('#F8F9FA'),
    dangerDefault: toMantineColor('#FA5252'),
    dangerEmphasized: toMantineColor('#E03131'),
    helpDefault: toMantineColor('#9775FA'),
    helpEmphasized: toMantineColor('#845EF7'),
    helpMuted: toMantineColor('#B197FC'),
    helpSubtle: toMantineColor('#E5DBFF'),
    successDefault: toMantineColor('#37B24D'),
    successEmphasized: toMantineColor('#2B8A3E'),
    successMuted: toMantineColor('#40C057'),
    successSubtle: toMantineColor('#EBFBEE'),
    infoDefault: toMantineColor('#4DABF7'),
    infoEmphasized: toMantineColor('#339AF0'),
    infoMuted: toMantineColor('#74C0FC'),
    infoSubtle: toMantineColor('#D0EBFF'),
    infoOnInfo: toMantineColor('#FFFFFF'),
    errorDefault: toMantineColor('#F03E3E'),
    errorEmphasized: toMantineColor('#C92A2A'),
    errorMuted: toMantineColor('#FA5252'),
    errorSubtle: toMantineColor('#FFE3E3'),
    warningDefault: toMantineColor('#F59F00'),
    warningEmphasized: toMantineColor('#E67700'),
    warningMuted: toMantineColor('#FAB005'),
    warningSubtle: toMantineColor('#FFF9DB'),
    inputsLabel: toMantineColor('#212529'),
    inputsDetail: toMantineColor('#868E96'),
    inputsPlaceholder: toMantineColor('#ADB5BD'),
    inputsText: toMantineColor('#212529'),
    inputsBigBgDisabled: toMantineColor('#F8F9FA'),
    inputsBigTextOnDisabled: toMantineColor('#CED4DA'),
    inputsBigIconDefault: toMantineColor('#495057'),
    inputsBigIconMuted: toMantineColor('#868E96'),
    inputsBigHover: toMantineColor('#F8F9FA'),
    inputsBigTextActive: toMantineColor('#1864AB'),
    inputsBigBgActive: toMantineColor('#E7F5FF'),
    inputsBigBgActive2: toMantineColor('#228BE6'),
    inputsSmallBgDefault: toMantineColor('#E9ECEF'),
    inputsSmallBgMuted: toMantineColor('#E9ECEF'),
    inputsSmallIconDefault: toMantineColor('#FFFFFF'),
    inputsSmallIconMuted: toMantineColor('#ADB5BD'),
    inputsSmallIconSubtle: toMantineColor('#F8F9FA'),
    dataDisplayBgDefault: toMantineColor('#CED4DA'),
    actionsBgDisabled: toMantineColor('#E9ECEF'),
    actionsTextOnDisabled: toMantineColor('#ADB5BD'),
    actionsPrimaryBgFilledHover: toMantineColor('#4263EB'),
    actionsPrimaryBgOutlineHover: toMantineColor('#EDF2FF'),
    actionsPrimaryBgQuietHover: toMantineColor('#EDF2FF'),
    actionsPrimaryBgDestructiveHover: toMantineColor('#F03E3E'),
    actionsSecondaryBgFilledHover: toMantineColor('#495057'),
    actionsSecondaryBgQuietHover: toMantineColor('#F8F9FA'),
    actionsSecondaryBgOutlineHover: toMantineColor('#F8F9FA'),
  },
  other: {
    fontSizes: {
      xxxs: 8,
      xxs: 10,
    },
  },
  headings: {
    fontFamily: 'IRANSansFaNum',
  },
};
