export const householderFormIds = {
  form: 'householder-identity-form',
  firstNameInput: 'householder-first-name',
  lastNameInput: 'householder-last-name',
  fatherNameInput: 'householder-father-name',
  nationalIdInput: 'householder-nationalId',
  issuedAtInput: 'householder-issuedAt',
  religionInput: 'householder-religion',
  genderInput: 'householder-gender',
  dobInput: 'householder-date-of-birth',
  submitBtn: 'householder-identity-submit-button',
  editBtn: 'householder-identity-edit-button',
  cancel: 'householder-identity-cancel-button',
  idPrefix: 'householder-identity',
} as const;
