name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  verify:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint and Format
        run: npm run lint:ci

      - name: Spell Check
        run: npm run spell

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

  chromatic:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      APP_API_ENDPOINT: /graphql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # NOTE: required because https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code-and-above
          fetch-depth: 0

      - uses: volta-cli/action@v3
      - name: Install dependencies
        run: npm ci

      - name: Deploy Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # NOTE: Option to prevent the workflow from failing

  cypress-run:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: Preview

    env:
      PORT: 5000
      APP_API_ENDPOINT: /graphql
      API_PROXY_TARGET: https://the-charity-backend-staging.herokuapp.com/graphql

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wake the server up
        run: curl https://the-charity-backend-staging.herokuapp.com/graphql
      - name: Run E2E tests
        uses: cypress-io/github-action@v4
        with:
          parallel: true
          start: npx vite preview --port ${{ env.PORT }}
          build: npm run build
          wait-on: http://127.0.0.1:${{ env.PORT }}
          wait-on-timeout: 20
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Component tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          component: true
          start: npx vite preview --port ${{ env.PORT }}
          build: npm run build
          wait-on: http://127.0.0.1:${{ env.PORT }}
          wait-on-timeout: 20
